### ISSUE TITLE
pep8 compliance

### ISSUE THREAD

**Issue by andymckay** [mozilla/minion-backend#338]
Anyone object to making the backend pep8 compliant?

**Comment by marumari** [comment]
I don't -- and in fact, I've been fixing things up as I've gone along -- but I would ask to wait until @ygjb gets in his big database update so we can do it all at once.

I do agree that PEP8 compliance will make everything much easier to work with, and I'll update this issue when we're good to start.

**Comment by andymckay** [comment]
Ok, i'll do it when @ygjb lands his database update.
