### ISSUE TITLE
User and group

### ISSUE THREAD

**Issue by andymckay** [mozilla/minion-backend#339]
The documentation suggests setting up a user account `minion`:

https://github.com/mozilla/minion-backend/blob/master/README.md

The supervisor confs use a user called `minion-backend`:

https://github.com/mozilla/minion-backend/blob/master/etc/minion-backend.supervisor.conf#L15

Presuming we can just one or the other all the way through?

**Comment by marumari** [comment]
Yes, that's correct.  It should just be minion.

**Comment by april** [comment]
All of the documentation should now be rewritten:

http://minion.readthedocs.org/en/latest/

Let me know if you find any errors like this in the new docs.  Thanks!
